# Site settings
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: ingrid.e
description: Ingrid Epure. Engineer at Intercom. Speaker
url: "ingride.xyz"
twitter_username: ingridepure
default_img:

# Profile settings
name: ingrid.e
profile_img: /assets/images/ingrid.gif
profile: Ingrid wants to make the world simpler. She's starting with Intercom's production systems. She talks and cares deeply about demystifying the tech culture and wants to make it more accessible and open. She is a DublinJs co-organizer and a mentor for women in tech communities. It's not entirely clear if she's really a unicorn whisperer or a vampire, but mentioning them makes bio's less awkward.
social:
  github: https://github.com/ingride
  twitter: https://twitter.com/ingridepure

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
