# Site settings
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: ingrid.e
description: Ingrid Epure. Engineer at Intercom. Speaker
url: "ingride.xyz"
twitter_username: ingridepure
default_img:

# Profile settings
name: ingrid.e
profile_img: /assets/images/ingrid.gif
profile: Engineer at Intercom . Speaker . Makes the world simpler, one production system at a time . @dublinjs co-organizer . Travels often .
social:
  github: https://github.com/ingride
  twitter: https://twitter.com/ingridepure

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
